language:
  - ruby
  - node_js

rvm:
  - 2.5.1

install:
  - bundle install
  - npm install

script:
  - npm run build

deploy:
  provider: pages

  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN

  local-dir: _site
  target-branch: gh-pages

  on:
    branch: master
